<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/menu.css')?>" />
<div id="menu">
	<div class="direction-strategique">
		<a href="<?php echo $this->baseUrl('direction-strategique')?>">Direction Strat&eacute;gique</a>
	</div>
	<div class="drh">
		<a href="<?php echo $this->baseUrl('drh')?>">DRH</a>
	</div>
	<div class="maintenance">
		<a href="<?php echo $this->baseUrl('maintenance')?>">Maintenance</a>
	</div>
	<div class="planning">
		<a href="<?php echo $this->baseUrl('planning')?>">Planning</a>
	</div>
	<div class="commercial">
		<a href="<?php echo $this->baseUrl('commercial')?>">Commercial</a>
	</div>
	<div class="exploitation">
		<a href="<?php echo $this->baseUrl('exploitation')?>">Exploitation</a>
	</div>
	<div class="logistique">
		<a href="<?php echo $this->baseUrl('logistique')?>">Logistique</a>
	</div>
</div>