<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/menu.css')?>" />
<nav id="menu">
	<ul>
		<li>
			<a href="<?php echo $this->baseUrl('strategie')?>">
				<div class="fils"><img src="<?php echo $this->baseUrl('img/strategie.png'); ?>" />Direction Stratégique</div>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->baseUrl('drh')?>">
				<div class="fils"><img src="<?php echo $this->baseUrl('img/drh.png'); ?>" />Ressources Humaines</div>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->baseUrl('maintenance')?>">
				<div class="fils"><img src="<?php echo $this->baseUrl('img/maintenance.png'); ?>" />Maintenance</div>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->baseUrl('planning')?>">
				<div class="fils"><img src="<?php echo $this->baseUrl('img/planning.png'); ?>" />Planning</div>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->baseUrl('commercial')?>">
				<div class="fils"><img src="<?php echo $this->baseUrl('img/commercial.png'); ?>" />Service Commercial</div>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->baseUrl('exploitation')?>">
				<div class="fils"><img src="<?php echo $this->baseUrl('img/exploitation.png'); ?>" />Service d'Exploitation</div>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->baseUrl('logistique')?>">
				<div class="fils"><img src="<?php echo $this->baseUrl('img/logistique.png'); ?>" />Service de logistique</div>
			</a>
		</li>
	</ul>
</nav>