<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/menu.css')?>" />
<div id="menu">
	<div class="direction-strategique">
		<a href="<?php echo $this->baseUrl('strategie')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/strategie.png')?>" />Direction Strat&eacute;gique</div></a>
	</div>
	<div class="drh">
		<a href="<?php echo $this->baseUrl('drh')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/drh.png')?>" />Ressources humaines</div></a>
	</div>
	<div class="maintenance">
		<a href="<?php echo $this->baseUrl('maintenance')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/maintenance.png')?>" />Maintenance</div></a>
	</div>
	<div class="planning">
		<a href="<?php echo $this->baseUrl('planning')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/planning.png')?>" />Planning</div></a>
	</div>
	<div class="commercial">
		<a href="<?php echo $this->baseUrl('commercial')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/commercial.png')?>" />Commercial</div></a>
	</div>
	<div class="exploitation">
		<a href="<?php echo $this->baseUrl('exploitation')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/exploitation.png')?>" />Exploitation</div></a>
	</div>
	<div class="logistique">
		<a href="<?php echo $this->baseUrl('logistique')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/logistique.png')?>" />Logistique</div></a>
	</div>
</div>