<?php
	if (Zend_Auth::getInstance ()->hasIdentity ()) {
		?>
			<section id="connexion">
				<h2>MON ESPACE PRIVÉ</h2>
				<div class="deco">
					<?php 
						$member = Zend_Auth::getInstance()->getIdentity();
						echo 'Vous êtes connecté en tant que <br />' . $member->login_utilisateur;
					?>
				</div>
					<a href="<?php echo $this->baseUrl('connexion/deconnexion'); ?>">Déconnexion</a>
			</section>
		<?php
	}
	else {
		?>
			<section id="connexion">
				<h2>MON ESPACE PRIVÉ</h2>
				<?php echo $this->formConnexion; ?>
			</section>
		<?php
	}
?>