<section id="Planning">
	<?php echo $this->action('menuplanning','planning'); ?>
	<table>
		<thead>
			<th>N° Vol</th>
			<th>Départ</th>
			<th>Arrivé</th>
			<th>Pilotes</th>
			<th>Avion</th>
			<th>Remarque</th>
		</thead>
		<tbody>
			<?php 

			foreach ($this->vol as $vol) {?>
			<tr>
				<td><?php echo $vol['numero_vol']; ?></td>
				<td><?php echo $vol['depart']; ?></td>
				<td><?php echo $vol['arrive']; ?></td>
				<td><?php echo $vol['pilotes']; ?></td>
				<td><?php echo $vol['avion']; ?></td>
				<td><?php echo $vol['remarque'] ?></td>
			</tr>				
			<?php }?>
		</tbody>
	</table>
</section>