<!-- Menu menuPlannig -->
<nav id="menuPlannig">
	<ul>
		<a href="<?php echo $this->baseUrl('planning/index'); ?>" title="Afficher la liste des vols">
			<li id="liste">
					<div>Liste des vols</div>
			</li>
		</a>
		<a href="<?php echo $this->baseUrl('planning/planification'); ?>" title="Afficher la liste des vols non planifiés">
			<li>
					<div>Plannification standard</div>
			</li>
		</a>
	</ul>
</nav>
<!-- Menu menuPlannig ends here -->