<section id="RessourceHumaine">
	<?php echo $this->action('menuplanning','planning'); ?>
	<table>
		<thead>
			<th>N° Vol</th>
			<th>Départ</th>
			<th>Arrivé</th>
			<th>Périodicité</th>
		</thead>
		<tbody>
			<?php foreach ($this->destination as $destination) {?>
			<tr>
				<td><?php echo $destination->numero_vol;?></td>
				<td><?php echo $destination->tri_aero_dep.' le '.date("d/m/Y à H:i",$destination->date_dep);?></td>
				<td><?php echo $destination->tri_aero_arr.' le '.date("d/m/Y à H:i",$destination->date_arr);?></td>
				<td><?php echo $destination->periodicite; ?></td>
			</tr>
			<?php }?>
	</table>
</section>