<section id="RessourceHumaine">
	<?php echo $this->action('menuplanning','planning'); ?>
	<table>
		<thead>
			<th>N° Vol</th>
			<th>Date</th>
			<th>Départ</th>
			<th>Arrivé</th>
		</thead>
		<tbody>
			<?php 
				$i = 0; 
				foreach ($this->destination as $destination) {
					?>
						<tr onclick="document.location.href='<?php echo $this->baseUrl('planning/planifier/id/'.$destination['id_destination'].'/heureD/'.$destination['heure_dep'].'/heureA/'.$destination['heure_arr']); ?>'" title="Cliquer sur la ligne pour planifier ce vols" class="lien">
							<td><?php echo $destination['numero_vol']; ?></td>
							<td><?php echo 'Le ' . date("d/m/Y",$destination['heure_dep']); ?></td>
							<td><?php echo $destination['tri_aero_dep'] . ' à ' . date("H:i",$destination['heure_dep']);?></td>
							<td><?php echo $destination['tri_aero_arr'] . ' le ' . date("d/m/Y à H:i",$destination['heure_arr']);?></td>
						</tr>
					<?php
					$i++;	
				}
			?>
	</table>
</section>