<?php $destination = $this->volAller;
$destinationRetour = $this->volRetour;
$classe = $this->classe;
if($classe ==1){
	$nomClasse = 'Économique';
}elseif($classe == 2){
	$nomClasse = 'Affaire';
}elseif($classe == 2.5){
	$nomClasse = 'Première';
}
$nbrPassager = $this->nbrPassager;
$typePassager = $this->typePassager;
setlocale (LC_TIME, 'fr_FR','fra'); ?>
<div class="detailsVol">
	<div class="detailsVolFils">
		<h2>Vol Aller <?php echo $destination['villeDepart'].' - '.$destination['villeArrive'];?></h2>
		<span><?php echo strftime("%A %d %B",$destination['heure_dep']);?></span><br/>	
		<div class="numero_vol"><?php echo $destination['numero_vol'].' '.$nomClasse;?></div>
		<div class="lieu">
			<div class="depart"><?php echo strftime("%H:%M",$destination['heure_dep']).' <span class="ville">'.$destination['villeDepart'].'</span>, '.$destination['depart'];?></div>
			<div class="arrive"><?php echo strftime("%H:%M",$destination['heure_arr']).' <span class="ville">'.$destination['villeArrive'].'</span>, '.$destination['arrive'];?></div>
		</div>	
	</div>	
</div>
<?php if(isset($destinationRetour) && $destinationRetour != ''){?>
<div class="detailsVol">
	<div class="detailsVolFils">
		<span><?php echo strftime("%A %d %B",$destinationRetour['heure_dep']);?></span><br/>	
		<div class="numero_vol"><?php echo $destinationRetour['numero_vol'].' '.$nomClasse;?></div>
		<div class="lieu">
			<div class="depart"><?php echo strftime("%H:%M",$destinationRetour['heure_dep']).' <span class="ville">'.$destinationRetour['villeDepart'].'</span>, '.$destinationRetour['depart'];?></div>
			<div class="arrive"><?php echo strftime("%H:%M",$destinationRetour['heure_arr']).' <span class="ville">'.$destinationRetour['villeArrive'].'</span>, '.$destinationRetour['arrive'];?></div>
		</div>	
	</div>
</div>
<?php }?>
