<script>
    $(function() {
        var c = new Date();
        var date = c.getDate()+'-'+(c.getMonth()+1)+'-'+c.getFullYear();
        $( "#datepickerdeb" ).datepicker({dateFormat :'d-m-yy', minDate: 0, numberOfMonths: 2, showButtonPanel: true}).val(date);
        $("#datepickerfin").datepicker({dateFormat :'d-m-yy', minDate: 0, numberOfMonths: 2, showButtonPanel: true}).val(date);
        $("#datepickerdeb").change(function(){
            var d = $("#datepickerdeb").datepicker('getDate');
        
            var n = new Date(d.getFullYear(), d.getMonth(), d.getDate());
            var m = d.getDate()+'-'+(d.getMonth()+1)+'-'+d.getFullYear();
     
            $("#datepickerfin").datepicker({dateFormat :'d-m-yy', minDate: n, numberOfMonths: 2, showButtonPanel: true}).val(m);
        });
    });
    $(function() {
 
 
        $( "#dialog-form" ).dialog({
            autoOpen: false,
            height: 550,
            width: 750,
            modal: true,
            buttons: {
                Fermer: function() {
                    $( this ).dialog( "close" );
                }
            },
            close: function() {
                allFields.val( "" ).removeClass( "ui-state-error" );
            }
        });
 
        $( "#create-projet" )
            .button()
            .click(function() {
                $( "#dialog-form" ).dialog( "open" );
            });
    });
</script>
<div id="accueil">
	<div id="reservation">
		<div class="bgRed"><span>Réservation</span></div>
        <div class="reservation">
    		<?php echo $this->formCommercial; ?>
        </div>
	</div>
</div>

