<div class="recherche">
    <form method="POST" action="<?php echo $this->baseUrl('commercial/detailsrecherche');?>">
        <input type="hidden" name="victor" value="victor"/>
        <div class="aller">
            <div class="titre">
                <h2>Vol aller</h2>
            </div>  
            <table>
                <thead>
                    <th>Numero vol</th>
                    <th>Départ</th>
                    <th>Arrivée</th>
                    <th>Prix</th>
                    <th>Réserver</th>
                </thead>
                <tbody>
                    <?php foreach ($this->tabVol as $vol) {?>
                        <tr>
                            <td><?php echo $vol['numero_vol']; ?></td>

                            <td>
                                <?php 
                                    echo $vol['depart'];
                                    setlocale (LC_TIME, 'fr_FR','fra'); 
                                    echo strftime("%A %d %B %H:%M",$vol['heure_dep']);  
                                ?>
                            </td>

                            <td>
                                <?php 
                                    echo $vol['arrive']; 
                                    echo strftime("%A %d %B %H:%M",$vol['heure_arr']);
                                ?>
                            </td>

                            <td><?php echo $vol['prix'].'€'; ?></td>

                            <td><input type="radio" name="volAller" value="<?php echo $vol['numero_vol'].'/'.$vol['heure_dep'];?>"/></td>
                        </tr>
                    <?php }?>
                </tbody>
            </table>
        </div>
        <?php if(isset($this->tabVolRetour) && $this->tabVolRetour != ''){?>
            <div class="retour">
                <div class="titre">
                    <h2>Vol retour</h2>
                </div>
                <table>
                    <thead>
                        <th>Numero vol</th>
                        <th>Départ</th>
                        <th>Arrivée</th>
                        <th>Prix</th>
                        <th>Réserver</th>
                    </thead>
                    <tbody>
                        <?php foreach ($this->tabVolRetour as $volRetour) {?>
                            <tr>
                                <td><?php echo $volRetour['numero_vol']; ?></td>

                                <td>
                                    <?php 
                                        echo $volRetour['depart']; 
                                        echo strftime("%A %d %B %H:%M",$volRetour['heure_dep']);
                                    ?>
                                </td>

                                <td>
                                    <?php 
                                        echo $volRetour['arrive']; 
                                        echo strftime("%A %d %B %H:%M",$volRetour['heure_arr']);
                                    ?>
                                </td>

                                <td><?php echo $volRetour['prix'].'€'; ?></td>

                                <td><input type="radio" name="volRetour" value="<?php echo $volRetour['numero_vol'].'/'.$volRetour['heure_dep'];?>"/></td>
                            </tr>
                        <?php }?>
                    </tbody>
                </table>
            </div>
        <?php }?>
        <input type="submit" name="reserve" value="Réserver" />
    </form>
</div>