<?php  $reservation = $this->reservation;
$reservation_retour = $this->reservationRetour;
?>
<div>
	<div class="detailsAller">
		<p>Vous venez de réserver un vol <?php echo $reservation['trajet'];?> au départ de <?php echo $reservation['depart'];?> à destination de <?php echo $reservation['arrive'];?></p>
		<p>Vous décolerez à <?php echo date('H\hi',$reservation['heure_dep']).' le '.date('d/m/Y',$reservation['heure_dep']);?> (Durée estimée à <?php echo $reservation['duree'];?>).</p>
		<p>Vous avez réservé pour <?php echo $reservation['nbrPassager'];?> personne(s) pour un total de <?php echo intval($reservation['prix']);?>€.</p>
	</div>
	<?php if(isset($reservation_retour) && $reservation_retour != ''){?>
		<div class="detailsRetour">
			<p>Vous décolerez au retour à <?php echo date('H\hi',$reservation_retour['heure_dep']).' le '.date('d/m/Y',$reservation_retour['heure_dep']);?> (Durée estimée à <?php echo $reservation_retour['duree'];?>).</p>
		</div>
	<?php }?>
	

<?php foreach ($this->clients as $client) {?>
	<p><?php echo $client->civilite.' '.$client->nom_client.' '.$client->prenom_client;?></p>
<?php }?>

</div>