<section id="strategie">
	<a href="#editVol" rel="popup_editVol_" class="poplight poplightedit">
		<button class="bgRedBtn" style="float:none;">Créer un vol</button>
	</a>
	<br />
	<br />
	<?php 
		if (count($this->destination) > 0) {
			?>
				<table>
					<thead>
						<th>Vol N°</th>
						<th>Départ</th>
						<th>Arrivée</th>
						<th>départ</th>
						<th>arrivée</th>
						<th>Périodicité</th>
						<th colspan="2">Action</th>
					</thead>
					<tbody>
						<?php foreach ($this->destination as $value) {?>
						
						<tr>
							<td><?php echo $value['numero_vol'];?></td>
							<td><?php echo $value['tri_aero_dep'];?></td>
							<td><?php echo $value['tri_aero_arr'];?></td>
							<td><?php echo date("d/m/Y",$value['date_dep']) . ' - ' . date("H:i",$value['heure_dep']);?></td>
							<td><?php echo date("d/m/Y",$value['date_arr']) . ' - ' . date("H:i",$value['heure_arr']);?></td>
							<td><?php echo $value['periodicite'];?></td>
							<td><a href="#editVol" rel="popup_editVol_<?php echo $value['numero_vol'];?>" class="poplight poplightedit" title="Modifier"><button class="modifier">modifier</button></a></td>
							<td><a href="" title="Supprimer"><button class="supprimer">supprimer</button></a></td>
						</tr>

						<?php }?>
					</tbody>
				</table>
				<div class="formulaire">
					<!-- popup nouveau pays -->
					<?php echo $this->action('nouveaupays','strategie'); ?>

					<!-- popup nouvelle ville -->
					<?php echo $this->action('nouvelleville','strategie'); ?>

					<!-- popup nouvel aeroport -->
					<?php echo $this->action('nouvelaeroport','strategie'); ?>
				
					<!-- popup nouveau vol -->
					<?php echo $this->action('nouveau','strategie'); ?>

					<?php 
						foreach ($this->destination as $value) {
							echo $this->action('nouveau','strategie', null, array('numero_vol' => $value['numero_vol']));
						} 
					?>
				</div>

			<?php
		} 
		else {
			echo "Aucune destination n'est enregistrée";
		}
	?>
</section>
