<section id="strategie" class="testr">
	<a href="#editVol" rel="popup_editVol_" class="poplight">
		<button class="bgRedBtn" style="float:none;">Créer un vol</button>
	</a>
	<br />
	<br />
	<?php 
		if (count($this->destination) > 0) {
			?>
				<table>
					<thead>
						<th>Vol N°</th>
						<th>Départ</th>
						<th>Arrivée</th>
						<th>Heure de départ</th>
						<th>Heure d'arrvivée</th>
						<th>date de départ</th>
						<th>date d'arrivée</th>
						<th>Périodicité</th>
						<th></th>
						<th></th>
					</thead>
					<tfoot>
						<td></td>
					</tfoot>
					<tbody>
						<?php foreach ($this->destination as $value) {?>
						<tr>
							<td><?php echo $value['numero_vol'];?></td>
							<td><?php echo $value['tri_aero_dep'];?></td>
							<td><?php echo $value['tri_aero_arr'];?></td>
							<td><?php echo date("H:i",$value['heure_dep']);?></td>
							<td><?php echo date("H:i",$value['heure_arr']);?></td>
							<td><?php echo date("d-m-Y",$value['date_dep']);?></td>
							<td><?php echo date("d-m-Y",$value['date_arr']);?></td>
							<td><?php echo $value['periodicite'];?></td>
							<td><a href=""><button>mofifier</button></a></td>
							<td><a href=""><button>supprimer</button></a></td>
						</tr>
						<?php echo $this->action('nouveau','strategie', null, array('numero_vol' => $value['numero_vol'])); ?>
						<?php }?>
					</tbody>
				</table>
			<?php
		} 
		else {
			echo "Aucune destination n'est enregistrée";
		}
	?>
</section>

<!-- popup nouveau vol -->
<?php echo $this->action('nouveau','strategie'); ?>

<!-- popup nouveau pays -->
<?php echo $this->action('nouveaupays','strategie'); ?>

<!-- popup nouvelle ville -->
<?php echo $this->action('nouvelleville','strategie'); ?>

<!-- popup nouvel aeroport -->
<?php echo $this->action('nouvelaeroport','strategie'); ?>