<!-- <div class="droite min-width">
	<div class="droitefils">
		<div id="popup_modifvol" style="display:none">
			<header class="strategie">
				<div class="strategie1 strat-pos"></div>
				<div class="strategie2 strat-pos">
					<div class="strategiefils">
						<div class="titre">
							<span><?php echo $this->translate('Modification d\'un Vol')?></span>
						</div>
					</div>
				</div>
			</header>
			<section class="newVol">
				<div class="newVol1 NV-pos"></div>
				<div class="newVol2 NV-pos">
					<div class="newVolfils">
						<?php echo $this->formNouveauVol; ?>
					</div>
				</div>
			</section>
		</div>
 -->