<?php
	echo '<script>
	    $(function() {
	    	$(".timepickerdeb'.$this->id_destination.'").timepicker();
			$(".timepickerfin'.$this->id_destination.'").timepicker();
	        $(".datepickerdeb'.$this->id_destination.'" ).datepicker({dateFormat :"dd-mm-yy", minDate: 0});
	    });
	</script>';

?>
<!-- popup nouveau vol -->
<div id="popup_editVol_<?php echo $this->id_destination;?>" class="popup_block rouleau-fenetre">
	<header class="rouleau-fenetre-titre">
		<span><?php echo $this->translate('Création d\'un Vol')?></span>
	</header>
	<section class="rouleau-fenetre-section">
				<a href="#?editvol" rel="popup_ajouterPays" class="poplight"><button class="ajouter_pays">Ajouter un pays</button></a>
				<a href="#?editvol" rel="popup_ajouterVille" class="poplight"><button class="ajouter_ville">Ajouter une ville</button></a>
				<a href="#?editvol" rel="popup_ajouterAeroport" class="poplight"><button class="ajouter_aeroport">Ajouter un aéroport</button></a>
				<?php echo $this->formNouveauVol; ?>
	</section>
</div>