<?php
	echo '<script>
	    $(function() {
	    	$(".timepickerdeb'.$this->numero_vol.'").timepicker();
			$(".timepickerfin'.$this->numero_vol.'").timepicker();
	        $(".datepickerdeb'.$this->numero_vol.'" ).datepicker({dateFormat :"dd-mm-yy", minDate: 0});
	        $(".datepickerdeb'.$this->numero_vol.'").change(function(){
	            var d = $(".datepickerdeb'.$this->numero_vol.'").datepicker("getDate");
	        
	            var n = new Date(d.getFullYear(), d.getMonth(), d.getDate());
	     
	            $(".datepickerfin'.$this->numero_vol.'").datepicker({dateFormat :"dd-mm-yy", minDate: n});
	        });
	    });
	</script>';
	echo '<script>
		
	</script>';
?>
<!-- popup nouveau vol -->
<div id="popup_editVol_<?php echo $this->numero_vol;?>" class="popup_block rouleau-fenetre">
	<header class="rouleau-fenetre-titre">
		<span><?php echo $this->translate('Création d\'un Vol')?></span>
	</header>
	<section class="rouleau-fenetre-section">
				<a href="#?editvol" rel="popup_ajouterPays" class="poplight"><button class="ajouter_pays">Ajouter un pays</button></a>
				<a href="#?editvol" rel="popup_ajouterVille" class="poplight"><button class="ajouter_ville">Ajouter une ville</button></a>
				<a href="#?editvol" rel="popup_ajouterAeroport" class="poplight"><button class="ajouter_aeroport">Ajouter un aéroport</button></a>
				<?php echo $this->formNouveauVol; ?>
	</section>
</div>