<section id="Maintenance">
	<?php echo $this->action('menumaintenance','maintenance'); ?>

	Planning des maintenances prevue :<br/>
	<br/>
	<?php 
        $jour_now       = $this->jour_actuel;
        $annee_depart   = $this->annee_actuel;
        $mois_depart    = $this->mois_actuel;
		//Zend_Debug::dump($this->ligne);
	?>
	<font color="#FFCCCD">Maintenance en retard: Rouge </font><br/>
	<font color="#CCD1FF">Maintenance Fini : Bleu</font><br/>
	<br/>

	<?php 
		for ($i=0; $i <= 2 ; $i++) {

			if($i != 0){
				$mois_depart = str_pad($mois_depart+1, 2, "0", STR_PAD_LEFT);
			}else{
				$mois_depart = str_pad($mois_depart, 2, "0", STR_PAD_LEFT);
			}
			

			if ($mois_depart == 13){
				$mois_depart = 0;
				$annee_depart = $annee_depart+1;
			}
			?>
				<table width="325px">
					<thead>
						<tr>
							<th colspan="5"><?php echo $this->NameMois[$mois_depart].' - '.$annee_depart ?></th>
						</tr>
						<tr>
							<th width="55px">Jour</th>
							<th width="55px">Imma..</th>
							<th width="100px">Note</th>
							<th colspan="2">Action</th>
						</tr>
					</thead>
					<tbody>
						<?php 
							for ($numday = 1; $numday <= date("t" ,mktime(0 , 0, 0, $mois_depart, 1, $annee_depart)); $numday++) {

								$jourcalendrier = str_pad($numday, 2, "0", STR_PAD_LEFT);

								// Colorie les jours déjà passés
								if ( $jour_now >= $numday && $i == 0 ) {
									if ( isset($this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['date_eff']) && isset($this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['duree_eff']) ) {

										if ( $this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['date_eff'] == 0 && $this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['duree_eff'] == 0) {
											$couleur = '#FFCCCD'; // Rouge
										}
										else {
											$couleur = '#CCD1FF'; // Bleu
										}

									}
									else {
										$couleur = '#E1E1E1'; // Gris
									}
									
								}
								else {
									if ( isset($this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['date_eff']) && isset($this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['duree_eff']) ) {

										if ( $this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['date_eff'] != 0 && $this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['duree_eff'] != 0) {

											$couleur = '#CCD1FF'; // Bleu
										}
									}
									else {
										$couleur = 'none'; // aucune couleur
									}
									
								}

								?>
									<tr style="background-color:<?php echo $couleur; ?>;">
										<td><?php echo $this->DayNames[date("w", mktime(0 , 0, 0, $mois_depart, $jourcalendrier, $annee_depart))].' '.$jourcalendrier; ?></td>
									
										<?php 
											if (isset($this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['immatriculation'])) { 
												?>
													<td><?php echo $this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['immatriculation']; ?></td><td>
													<?php 
													
														if (strlen($this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['note']) >= 40 ) {
															echo substr($this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['note'],0,40) . '...'; 
														}

														else { 
															echo $this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['note']; 
														}
													?></td>
													<td width="8px">
														<a href="<?php echo $this->baseUrl('maintenance/modifier/immatriculation/' . $this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['immatriculation']); ?>" title="Modifier">
															<button class="modifier">Modifier</button>
														</a>
													</td>
													<td width="8px">
														<a href="<?php echo $this->baseUrl('maintenance/supprimer/immatriculation/' . $this->ligne[$annee_depart][$mois_depart][$jourcalendrier]['immatriculation']); ?>" title="Supprimer">
															<button class="supprimer">Supprimer</button>
														</a>
													</td>
												<?php 
											}
											else { 
												?>
													<td></td>
													<td></td>
													<td></td>
													<td></td>
												<?php 
											}
										?>

									</tr>
								<?php
							}
						?>
					</tbody>
				</table>
			<?php 
		}
	?>
</section>