<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/menu.css')?>" />
<div id="menu">
	<div class="direction-strategique">
		<a href="<?php echo $this->baseUrl('avion/ajouter')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/planning.png')?>" /><br/>Ajouer un Avion</div></a>
	</div>
	<div class="drh">
		<a href="<?php echo $this->baseUrl('')?>"><div class="fils"><img src="<?php echo $this->baseUrl('img/planning.png')?>" /><br/>Calendrier des interventions</div></a>
	</div>
	
</div>