<?php echo $this->action('menumaintenance','maintenance'); ?>

<br/>
Liste des avion disponible pour une maintenance :<br/>
<br/>

<section id="">
	<table>
		<thead>
			<th>Model</th>
			<th>Immatriculation</th>
			<th>Heur de vol</th>
			<th>Heur depuis la derniere revision </th>
			<th>Maintenance</th>
		</thead>
		<tbody>
			<?php 
			$HeureMax = 300;
			$HeureMin = 100;
			foreach ($this->avion as $avion) { 


				 if ($avion['heure_depuis_revision'] >=  $HeureMax && $avion['date_prevue'] == 0 ){
				 	echo '<tr bgcolor=#F08080>';
				 }else{
					if ($avion['heure_depuis_revision'] >=  $HeureMin && $avion['date_prevue'] == 0 ){
					 	echo '<tr bgcolor=#FFA07A>';
					 }else{
					 	echo '<tr>';
					 }
				 }

				?>

			


				<td><?php echo $avion['nom_model']; ?></td>
				<td><?php echo $avion['immatriculation']; ?></td>
				<td><?php echo $avion['heure_vol_total']; ?></td>
				<td><?php echo $avion['heure_depuis_revision']; ?></td>
				<?php if ($avion['date_prevue'] == 0){
					
					echo '<td><a href="'.$this->baseUrl('maintenance/ajouter/immatriculation/' . $avion['immatriculation']).'" title="Ajouter Maintenance"><button class="ajouter">Ajouter</button></a></td>';
				}else{ 
					echo '<td><a href="'.$this->baseUrl('maintenance/afficher').'" title="Ajouter Maintenance">Du :'.date('d/m/Y', $avion['date_prevue']).' ('.$avion['duree_prevue'].' jours)</a></td>';
					
				}?>

			</tr>
			<?php }?>
		</tbody>
	</table><br/>
	*Legende :<br/>
		<font color="#F08080">Maintenance a prevoir : <br/>Rouge ( Nombre d'heurs superieur a <?php echo $HeureMax; ?> heurs de vol )</font><br/>
		<font color="#FFA07A">Maintenance pour bientot : <br/>Orange( Nombre d'heurs superieur a <?php echo $HeureMin; ?> heurs de vol )</font><br/>
</section>