<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/menu.css')?>" />
<div id="menu" align="center">
	Ajouter un appareil :
	<br/><br/>
	<form method="post" action="#" align="left">
	        <label>Model : </label>
	        <select>
	          <option value="">Bohing 437</option>
	          <option value="">Bohing 499</option>
	        </select>
	        <br/>
	      	<label>Immatriculation: </label>	
	      	<input type="text" name="" id="" size="30" maxlength="10" />
	        <br/>
	    	<label>Heure de vol total : </label>	
	      	<input type="text" name="" id="" size="30" maxlength="10" />
	        <br/>
	        <label>Heure depuis la derniere revision: </label>	
	      	<input type="text" name="" id="" size="30" maxlength="10" />
	        <br/>
	    <br/>
	</form>
	<INPUT TYPE="submit" NAME="nom" VALUE="Valider">
</div>