<section id="RessourceHumaine">
	<?php echo $this->action('menurh','ressourcehumaine'); ?>

	<?php $pilote = $this->pilote;
	$utilisateur = $this->utilisateur;?>
	<ul>
		<li>
			Nom : <?php echo $utilisateur->nom_utilisateur; ?>
		</li>
		<li>
			Prénom : <?php echo $utilisateur->prenom_utilisateur; ?>
		</li>
		<li>
			Brevet : 
		</li>
		<li>
			<table>
				<thead>
					<th>Nom du brevet</th>
					<th>Obtention du brevet</th>
					<th>Date de revalidation</th>
					<th>Supprimer</th>
				</thead>
				<tbody>			
				<?php foreach ($this->brevet as $brevet) {
					$tableBrevetType = new TBrevet;
					$brevetTypeRequest = $tableBrevetType->select()->where('id_brevet ='.$brevet->id_brevet );
					$brevetType = $tableBrevetType->fetchRow($brevetTypeRequest);
					$dateRevalidation = 60*60*24*365*$brevetType->temps_validite+$brevet->date_obtention;
					?>
					<tr>
						<td><?php echo $brevetType->nom_brevet;?></td>
						<td><?php echo date("d-m-Y",$brevet->date_obtention);?></td>
						<td><?php echo date("d-m-Y",$dateRevalidation);?></td>
						<td>
							<a href="<?php echo $this->baseUrl('ressourcehumaine/supprimerbrevet/idBrevet/'.$brevet->id_pilote_brevet.'/idUtilisateur/'.$utilisateur->id_utilisateur); ?>" title="Supprimer">
								<button class="supprimer">supprimer</button>
							</a>
						</td>
					</tr>
				<?php }?>		
				</tbody>	
			</table>
		</li>
		<li>
			<a href="#attribBrevet" rel="popup_attribBrevet" class="poplight poplightedit">
				<button>Attribuer un brevet</button>
			</a>
		</li>
		<li>
			<a href="#creerBrevet" rel="popup_creerBrevet" class="poplight poplightedit">
				<button>Créer un brevet</button>
			</a>
		</li>
	</ul>
	<div class="formulaire">
		<?php echo $this->action('attribuer','ressourcehumaine', null, array('idPilote'=>$pilote->id_pilote, 'idUtilisateur'=>$pilote->id_utilisateur)); ?>
		<?php echo $this->action('creerbrevet','ressourcehumaine'); ?>
	</div>
</section>