<section id="RessourceHumaine">
	<?php echo $this->action('menurh','ressourcehumaine'); ?>
	<span class="error">
		<?php
			$array =  $this->messages;
			foreach ($array as $key => $value) {
				echo $value;
			}
		?>
	</span>
	<br/>
	<?php echo $this->action('filtre','ressourcehumaine'); ?>
	<?php
		// on recupere tous les employés de la base de donnée
		$utilisateurs = $this->utilisateurs;

		// si on en a plus d'une, on les affiches
		if (count($utilisateurs) > 0) {
			?>
				<table>
					<thead>
						<th>N° Employé</th>
						<th>Identité</th>
						<th>Adresse</th>
						<th>Service</th>
						<th colspan="2">Action</th>
					</thead>
					<tbody>
							<?php 
								foreach ($this->utilisateurs as $utilisateur) {
									// on charge le modelutilisateur
									$tableUtilisateur = new TUtilisateur;

									// Requete par clé primaire
						            $user = $tableUtilisateur	->find($utilisateur->id_utilisateur)
						                                    	->current();

					                // Recherche du service de l'utilisateur
					                $service = $user->findParentRow('TService');
					                
									?>
										<tr onclick="document.location.href='<?php echo $this->baseUrl('ressourcehumaine/detail/id/' . $utilisateur->id_utilisateur); ?>'" title="Cliquer sur la ligne pour visiter le detail de l'utilisateur" class="lien">
											<td><?php echo $utilisateur->id_utilisateur; ?></td>
											<td><?php echo utf8_encode($utilisateur->nom_utilisateur . ' ' . $utilisateur->prenom_utilisateur); ?></td>
											<td>
												<?php echo utf8_encode($utilisateur->adresse_utilisateur); ?><br />
												<?php echo $utilisateur->cp_utilisateur . ' - ' . utf8_encode($utilisateur->ville_utilisateur); ?>
											</td>
											<td><?php echo utf8_encode($service->nom); ?></td>
											<td><a href="#editEmploye" rel="popup_editEmploye_<?php echo $utilisateur->id_utilisateur;?>" class="poplight poplightedit" title="Modifier"><button class="modifier">modifier</button></a></td>
											<td><a href="<?php echo $this->baseUrl('ressourcehumaine/supprimer/id/' . $utilisateur->id_utilisateur); ?>" title="Supprimer"><button class="supprimer">supprimer</button></a></td>
										</tr>
									<?php
								}
							?>
					</tbody>
				</table>
				<div class="formulaire">
					<!-- popup nouvel employé -->
					<?php echo $this->action('editer','Ressourcehumaine'); ?>

					<?php 
						foreach ($utilisateurs as $utilisateur) {
							echo $this->action('editer','Ressourcehumaine', null, array('idUtilisateur' => $utilisateur->id_utilisateur));
						} 
					?>
				</div>
			<?php
		} 
		else { // sinon (aucun employé)
			// on affiche un message
			?>
				<div class="tableVide">
					<span>Aucun utilisateur n'est enregistré</span>
				</div>
				<div class="formulaire">
					<!-- popup nouvel employé -->
					<?php echo $this->action('editer','Ressourcehumaine'); ?>
				</div>
			<?php
		}
	?>
</section>