<!-- Menu gestion des contact -->
<nav id="menuRH">
	<ul>
		<a href="#?filtreUtilisateur" rel="popup_filtreUtilisateur" class="poplight" title="Filtrer les employés">
			<li id="filtrer">
					<div>Filtrer les employés</div>
			</li>
		</a>
		<?php
			if ($this->action != 'detail') {
				?>
					<a href="#editEmploye" rel="popup_editEmploye_" class="poplight poplightedit" title="Ajouter un employé">
						<li id="ajouter">
								<div>Ajouter un employé</div>
						</li>
					</<a>
				<?php
			}
		?>
		<a href="<?php echo $this->baseUrl('ressourcehumaine'); ?>" title="Afficher tous les employés">
			<li  id="listeResumer">
					<div>Afficher tous les employés</div>
			</li>
		</a>
	</ul>
</nav>
<!-- Menu gestion des contact ends here -->