<section id="RessourceHumaine">
	<ul>
		<?php $pilote = $this->pilote;
		$utilisateur = $this->utilisateur;?>
		<li>
			Nom : <?php echo $utilisateur->nom_utilisateur; ?>
		</li>
		<li>
			Prénom : <?php echo $utilisateur->prenom_utilisateur; ?>
		</li>
		<li>
			Brevet : 
		</li>
		<table>
			<thead>
				<th>Nom du brevet</th>
				<th>Obtention du brevet</th>
				<th>Date de revalidation</th>
			</thead>
			<tbody>			
			<?php foreach ($this->brevet as $brevet) {
				$tableBrevetType = new TBrevet;
				$brevetTypeRequest = $tableBrevetType->select()->where('id_brevet ='.$brevet->id_brevet );
				$brevetType = $tableBrevetType->fetchRow($brevetTypeRequest);
				$dateRevalidation = 60*60*24*365*$brevetType->temps_validite+$brevet->date_obtention;

				echo'
				<tr>
					<td>'.$brevetType->nom_brevet.'</td><td>'.date("d-m-Y",$brevet->date_obtention).'</td><td>'.date("d-m-Y",$dateRevalidation).'</td>
				</tr>';
			}?>		
			</tbody>	
		</table>
		<li>
			<a href="#attribBrevet" rel="popup_attribBrevet" class="poplight poplightedit">
				<button>Attribuer un brevet</button>
			</a>
		</li>
	</ul>
</section>

<?php echo $this->action('attribuer','ressourcehumaine', null, array('idPilote'=>$pilote->id_pilote, 'idUtilisateur'=>$pilote->id_utilisateur)); ?>