<section id="RessourceHumaine">
	<?php echo $this->action('menurh','ressourcehumaine'); ?>

	<?php $utilisateur = $this->utilisateur;?>
	<table>
		<thead>
			<th>N° Pilote</th>
			<th>Nom</th>
			<th>Prénom</th>
			<th>Adresse</th>
			<th>Nombre de brevets</th>
			<th colspan="2">Action</th>
		</thead>
		<tbody>
			<? foreach ($utilisateur as $utilisateurs) {
				$tablePilote = new TPilote;
				$piloteRequest = $tablePilote->select()->where('id_utilisateur ='.$utilisateurs->id_utilisateur);
        		$pilote = $tablePilote->fetchRow($piloteRequest);?>
				<tr>
					<td><?php echo $pilote->id_pilote; ?></td>
					<td><?php echo $utilisateurs->nom_utilisateur; ?></td>
					<td><?php echo $utilisateurs->prenom_utilisateur; ?></td>
					<td>
						<?php echo $utilisateurs->adresse_utilisateur; ?><br />
						<?php echo $utilisateurs->cp_utilisateur . ' - ' . $utilisateurs->ville_utilisateur; ?>
					</td>
					<?php $tableBrevetPilote = new TPiloteBrevet;
					$brevetPiloteRequest = $tableBrevetPilote->select()->where('id_pilote ='.$pilote->id_pilote);
	        		$brevetPilote = $tableBrevetPilote->fetchAll($brevetPiloteRequest);?>
					<td><?php echo count($brevetPilote); ?></td>
					<td>
						<a href="<?php echo $this->baseUrl('ressourcehumaine/detailspilote/idPilote/' . $utilisateurs->id_utilisateur); ?>" class="poplight poplightedit" title="Modifier"><button class="modifier">modifier</button></a>
					</td>
					<td>
						<a href="<?php echo $this->baseUrl('ressourcehumaine/supprimer/id/' . $utilisateur->id_utilisateur); ?>" title="Supprimer"><button class="supprimer">supprimer</button></a>
					</td>
				</tr>
				<?php }?>
		</tbody>
	</table>
</section>
