<?php echo $this->doctype(), PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="FR">
	<head>
		<?php
		    $this->headMeta()	->setHttpEquiv('Content-Type', 'text/html;X charset=utf-8')
                                ->setHttpEquiv('Content-Style-Type', 'text/css')
                                ->setHttpEquiv('lang', 'fr')
                                // ->setHttpEquiv('Refresh', '2')
                                ->setName('language', 'fr');
            echo $this->headMeta();

			$this->headLink()	->appendStylesheet('/css/resetcss.css')
                                ->appendStylesheet('/css/smoothness/jquery-ui-1.9.2.custom.css')
                                ->appendStylesheet('/css/style.css')
                                ->appendStylesheet('/css/rouleau.css')
                                ->appendStylesheet('/css/overlay.css');
			echo $this->headLink();
			
			$this->headScript()	->appendFile('/js/Jquery/jquery-1.8.3.js')					/////////////
								->appendFile('/js/Jquery/jquery-ui-1.9.2.custom.min.js')	//	JQuery
								->appendFile('/js/Jquery/jquery.easing.1.3.js')				/////////////
                                ->appendFile('/js/custom.js')                               /////////////////
                                ->appendFile('/js/rouleau.js')                              // 
                                ->appendFile('/js/overlay.js')                              // 
                                ->appendFile('/js/ajax.js')                                 // fichier perso
								->appendFile('/js/tutorial.js')                             //
                                ->appendFile('/js/ajaxRessourcesHumaines.js')
                                ->appendFile('/js/ajaxCommercial.js')
                                ->appendFile('/js/ajaxPlanning.js');				/////////////////
			echo $this->headScript();
		?>
		<title>Insset Airline</title>
	</head>
	<body>
        <div id="fade"></div>
		<div id="body">
            <!-- Header -->
            <header id="header">
                <?php echo $this->partial('header.phtml'); ?>
            </header>
            <!-- Header ends here -->

            <!-- Content -->
            <section id="content_wrap">
            	<div id="content">
                	<?php echo $this->layout()->content; ?>
                </div>
            </section>
            <!-- Content ends here -->

            <!-- Footer -->
            <footer id="footer">
                <?php
                    $registre = Zend_Registry::getInstance();
                    echo $this->partial('footer.phtml', array('annee' => $registre->config->app->copyright->annee));
                ?>
            </footer>
            <!-- Footer ends here -->
		</div>
	</body>
</html>
