<?php echo $this->doctype(), PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="FR">
	<head>
		<?php
            echo $this->headMeta();
			echo $this->headLink();
			echo $this->headScript();
		?>
		<title>Insset Airline</title>
	</head>
	<body>
        <div id="fade"></div>
		<div id="body">
            <!-- Header -->
            <header id="header">
                <?php echo $this->partial('header.phtml'); ?>
                <nav id="navbar">
                    <?php echo $this->navigation()->menu(); ?>
                </nav>
            </header>
            <!-- Header ends here -->

            <!-- Content -->
            <section id="content_wrap">
            	<div id="content">
                	<?php echo $this->layout()->content; ?>
                </div>
            </section>
            <!-- Content ends here -->

            <!-- Footer -->
            <footer id="footer">
                <?php
                    $registre = Zend_Registry::getInstance();
                    echo $this->partial('footer.phtml', array('annee' => $registre->config->app->copyright->annee));
                ?>
            </footer>
            <!-- Footer ends here -->
		</div>
	</body>
</html>
